{{- if .Values.kibana.enabled }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-kibana
  labels:
    component: {{ template "fullname" . }}-kibana
spec:
  replicas: {{ .Values.kibana.replicas }}
  selector:
    matchLabels:
     component: {{ template "fullname" . }}-kibana
  template:
    metadata:
      labels:
        component: {{ template "fullname" . }}-kibana
    spec:
      containers:
      - name: kibana
        image: cfontes/kibana-xpack-less:5.5.0
        env:
        - name: CLUSTER_NAME
          value: {{ .Values.common.env.CLUSTER_NAME }}
        {{- range $key, $value :=  .Values.kibana.env }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
        resources:
{{ toYaml .Values.kibana.resources | indent 12 }}
        ports:
        - containerPort: 5601
          name: kibana
          protocol: TCP
{{- end }}
