{{- if .Values.kibana.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-kibana
  labels:
    component: {{ template "fullname" . }}-kibana
spec:
  type: {{ .Values.common.serviceType }}
  ports:
  - port: {{ .Values.kibana.httpPort }}
    targetPort: 5601
    protocol: TCP
  selector:
    component: {{ template "fullname" . }}-kibana
{{- end }}
